packageRoots:
  core: packages
  mudout: packages/mudout
packages:
 - core:engine
instancePath: instances
systemRate: 500
minimumWait: 20
activeHotload: true
sessionEntrypoints:
  dashboard: dashboard
logPath: logs
enableLogging: true
